# Generated by Django 6.0.3 on 2026-03-12 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('errors', 'Has Errors'), ('imported', 'Imported')], default='pending', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlantingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('crop', models.CharField(max_length=100)),
                ('labor_cost', models.FloatField()),
                ('qty_planted', models.IntegerField()),
                ('target_qty', models.IntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'crop')},
            },
        ),
        migrations.CreateModel(
            name='StagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('week', models.CharField(blank=True, default='', max_length=20)),
                ('date', models.CharField(blank=True, default='', max_length=30)),
                ('crop', models.CharField(blank=True, default='', max_length=100)),
                ('labor_cost', models.CharField(blank=True, default='', max_length=30)),
                ('qty_planted', models.CharField(blank=True, default='', max_length=30)),
                ('target_qty', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='planting.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('error_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='planting.uploadbatch')),
            ],
        ),
    ]
